#!/usr/bin/env node
/**
 * sync-tokens.mjs — Zentrix token sync script (dev-time only, not bundled).
 *
 * Reads @zentrix/tokens (the monorepo package) and writes a fresh snapshot to
 * src/theme/zentrixTokens.ts so the pbiviz build has a static import it can
 * compile without needing the workspace symlink at bundle time.
 *
 * Usage:
 *   node scripts/sync-tokens.mjs           # write snapshot
 *   node scripts/sync-tokens.mjs --check   # exit 1 if snapshot is stale
 *
 * Prerequisite: run from the visual's package dir with @zentrix/tokens
 * available (pnpm install in the monorepo root wires the workspace symlink).
 * If the symlink is absent (isolated CI), the script falls back to a warning
 * and exits 0 so the build does not break — the committed snapshot is the
 * fallback in that case.
 *
 * Canonical source: zentrix/packages/tokens/src/
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CHECK_MODE = process.argv.includes("--check");
const OUT_PATH = resolve(__dirname, "../src/theme/zentrixTokens.ts");

// ---------------------------------------------------------------------------
// DISABLED — do not run. This generator was copied from the Bullet Chart and
// emits the WRONG export set for the Calendar Heatmap: it omits `fontFamily`,
// `resolveSurface`, `textPrimaryLight`, `textMutedDark`, `textTertiaryLight`
// (all imported by the visual) and adds bullet-only tokens. Running it would
// overwrite the correct, hand-maintained mirror and break the build.
//
// The mirror at ../src/theme/zentrixTokens.ts is the source of record; its
// hex values are sourced by hand from platform/packages/tokens/src/. A proper
// value-drift CHECKER (verify-only, never overwrite) is the intended
// replacement — see project-workspace-architecture (Phase 4).
// ---------------------------------------------------------------------------
console.error(
    "[sync-tokens] DISABLED: this generator is stale (copied from the Bullet\n" +
    "  Chart) and would break the Calendar Heatmap. The mirror in\n" +
    "  src/theme/zentrixTokens.ts is hand-maintained and correct. A verify-only\n" +
    "  drift-checker is planned; do not regenerate from this script."
);
process.exit(1);

// ---------------------------------------------------------------------------
// Attempt to load @zentrix/tokens via the workspace symlink.
// ---------------------------------------------------------------------------

let tokens;
try {
    // Use createRequire for CJS compat; the package exports ESM source so we
    // need to manually resolve the files directory.
    const tokensDir = resolve(__dirname, "../node_modules/@zentrix/tokens/src");
    // Dynamic import of the ESM source — requires Node ≥ 18
    const mod = await import(`file://${tokensDir}/index.ts`).catch(() => null);
    if (mod) {
        tokens = mod;
    }
} catch {
    tokens = null;
}

if (!tokens) {
    // The workspace symlink is not wired in this context.
    console.warn(
        "[sync-tokens] @zentrix/tokens not available via workspace link.\n" +
        "  The committed snapshot in src/theme/zentrixTokens.ts is the\n" +
        "  authoritative fallback. Wire the pnpm workspace to enable live sync."
    );
    // In --check mode, warn but do not fail (the snapshot may be correct even
    // if the live package is unavailable).
    process.exit(0);
}

// ---------------------------------------------------------------------------
// Extract the token values we care about.
// ---------------------------------------------------------------------------

const { palettes, themes, semantic, ramps, markRadius } = tokens;

const aurora_dark   = palettes.aurora.dark;
const aurora_light  = palettes.aurora.light;
const dark          = themes.dark;
const light         = themes.light;

/** Build the canonical snapshot content string. */
function buildSnapshot() {
    return `"use strict";

/**
 * Zentrix Design System — token snapshot for the Bullet Chart pbiviz build.
 *
 * THIS FILE IS GENERATED by scripts/sync-tokens.mjs.
 * Source of truth: zentrix/packages/tokens/src/ in the monorepo.
 *
 * DO NOT hand-edit hex values here — update the canonical source and run:
 *   node scripts/sync-tokens.mjs
 * or verify freshness with:
 *   node scripts/sync-tokens.mjs --check
 *
 * Generated: ${new Date().toISOString()}
 */

// Accent family — aurora palette
export const accent        = ${JSON.stringify(aurora_dark.accent)};
export const accentLine    = ${JSON.stringify(aurora_dark.accentLine)};
export const accentStrong  = ${JSON.stringify(aurora_dark.accentStrong)};
export const accentSoft    = ${JSON.stringify(aurora_dark.accentSoft)};
export const accentGlow    = ${JSON.stringify(aurora_dark.accentGlow)};

// CVD-safe semantic pair (Okabe–Ito)
export const posSafe       = ${JSON.stringify(semantic.posSafe)};
export const negSafe       = ${JSON.stringify(semantic.negSafe)};
export const posSafeStrong = ${JSON.stringify(semantic.posSafeStrong)};
export const negSafeStrong = ${JSON.stringify(semantic.negSafeStrong)};

// Dark surface
export const surfaceBase     = ${JSON.stringify(dark.surface.base)};
export const surfaceSubtle   = ${JSON.stringify(dark.surface.subtle)};
export const surfaceCard     = ${JSON.stringify(dark.surface.card)};
export const surfaceElevated = ${JSON.stringify(dark.surface.elevated)};
export const surfaceOverlay  = ${JSON.stringify(dark.surface.overlay)};

// Dark text
export const textPrimary   = ${JSON.stringify(dark.text.primary)};
export const textSecondary = ${JSON.stringify(dark.text.secondary)};
export const textTertiary  = ${JSON.stringify(dark.text.tertiary)};
export const textDisabled  = ${JSON.stringify(dark.text.disabled)};

// Derived — gridline + axis
export const gridLineDark  = ${JSON.stringify(dark.derived.gridLine)};
export const gridLineLight = ${JSON.stringify(light.derived.gridLine)};
export const axisTextDark  = ${JSON.stringify(dark.derived.axisText)};
export const axisTextLight = ${JSON.stringify(light.derived.axisText)};

// Light surface (theme-aware renderers)
export const surfaceElevatedLight = ${JSON.stringify(light.surface.elevated)};
export const surfaceOverlayLight  = ${JSON.stringify(light.surface.overlay)};

// Mark radius (px integers)
export const markRadiusCell  = ${parseInt(markRadius.cell, 10)};
export const markRadiusBar   = ${parseInt(markRadius.bar, 10)};
export const markRadiusLabel = ${parseInt(markRadius.label, 10)};

// Ramps
export const rampBrandDark: readonly string[]         = ${JSON.stringify(ramps.brand.dark)};
export const rampSequentialSafe: readonly string[]    = ${JSON.stringify(ramps.sequentialSafe.dark)};
export const rampDivergingSafeDark: readonly string[] = ${JSON.stringify(ramps.divergingSafe.dark)};
`;
}

const fresh = buildSnapshot();

if (CHECK_MODE) {
    let current;
    try {
        current = readFileSync(OUT_PATH, "utf8");
    } catch {
        console.error("[sync-tokens --check] Snapshot file missing:", OUT_PATH);
        process.exit(1);
    }
    // Compare only the data lines (skip the Generated timestamp line)
    const strip = s => s.split("\n").filter(l => !l.startsWith(" * Generated:")).join("\n");
    if (strip(current) !== strip(fresh)) {
        console.error("[sync-tokens --check] Snapshot is STALE. Run: node scripts/sync-tokens.mjs");
        process.exit(1);
    }
    console.log("[sync-tokens --check] Snapshot is up to date.");
    process.exit(0);
}

writeFileSync(OUT_PATH, fresh, "utf8");
console.log("[sync-tokens] Snapshot written to", OUT_PATH);
